version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"

  consumer:
    build: ./consumer
    restart: always
    depends_on:
      - rabbitmq

  producer:
      build: ./producer
      restart: always
      depends_on:
        - rabbitmq

